/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#4c4547",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        outline: "#7d7577",
        "outline-variant": "#cec4c7",
        primary: "#615e5e",
        "on-primary": "#ffffff",
        "primary-container": "#fff9f9",
        "on-primary-container": "#767272",
        "inverse-primary": "#cac5c5",
        secondary: "#8b4c4d",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdacac",
        "on-secondary-container": "#793d3e",
        tertiary: "#735c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fff9f4",
        "on-tertiary-container": "#8c6f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fcf9f8",
        "on-background": "#1b1c1c",
        gold: "#D4AF37",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1.5rem", full: "9999px" },
      spacing: {
        "section-gap": "80px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        base: "8px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        body: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
