/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fdf1f4",
        "surface-dim": "#e8d4d9",
        "surface-bright": "#fdf1f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faeaee",
        "surface-container": "#f6e1e7",
        "surface-container-high": "#f0d7de",
        "surface-container-highest": "#eaccd5",
        "surface-variant": "#e4d0d5",
        "on-surface": "#2b1518",
        "on-surface-variant": "#6b4048",
        "inverse-surface": "#3a1a22",
        "inverse-on-surface": "#fce8ed",
        outline: "#95626d",
        "outline-variant": "#d9b3bc",
        primary: "#7a1f35",
        "on-primary": "#ffffff",
        "primary-container": "#f9dde3",
        "on-primary-container": "#5c1526",
        "inverse-primary": "#e8a9bb",
        secondary: "#D6006C",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffd6ea",
        "on-secondary-container": "#8a004a",
        tertiary: "#735c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fff9f4",
        "on-tertiary-container": "#8c6f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fdf1f4",
        "on-background": "#2b1518",
        gold: "#D4AF37",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1.5rem", full: "9999px" },
      spacing: {
        "section-gap": "80px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        base: "8px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        body: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};